### ISSUE TITLE
tacotron项目

### ISSUE THREAD

**Issue by shakingWaves** [xiaominfc/flutter_tt#1]
你好，你的tacotron项目中针对标贝的数据，但是hparams.py中的sample_rate=16000,而标贝的采样率是48000。请问这个有影响吗？

**Comment by xiaominfc** [comment]
python中处理音频的库会对音频做降采样率处理！你也可以直接用48000 但是相应的参数就得调整一下

**Comment by xiaominfc** [comment]
> 你好，你的tacotron项目中针对标贝的数据，但是hparams.py中的sample_rate=16000,而标贝的采样率是48000。请问这个有影响吗？

python中处理音频的库会对音频做降采样率处理！你也可以直接用48000 但是相应的参数就得调整一下
